### ISSUE TITLE
WEBDATAROCKS for ANGULAR UNIVERSAL

### ISSUE THREAD

**Issue by LarozeMultiservices** [WebDataRocks/web-pivot-table#17]
Hi,

My project is based on ANGULAR 9 with UNIVERSAL and I need to install and work with WEBDATAROCKS. While I installed and build my project I ended up with the following error as 

   
_at __webpack_require__ (C:\Self\TFS\CRMMVC01\AngularFirebase\testProject\dist\testProject\server\main.js:26:30)
    at Module../node_modules/ng-webdatarocks/fesm2015/ng-webdatarocks.js (C:\Self\TFS\CRMMVC01\AngularFirebase\testProject\dist\testProject\server\main.js:211104:70)
    at __webpack_require__ (C:\Self\TFS\CRMMVC01\AngularFirebase\testProject\dist\testProject\server\main.js:26:30)
    at Object../src/app/app.component.ts (C:\Self\TFS\CRMMVC01\AngularFirebase\testProject\dist\testProject\server\main.js:237581:12)
    at __webpack_require__ (C:\Self\TFS\CRMMVC01\AngularFirebase\testProject\dist\testProject\server\main.js:26:30)                          at Object../src/app/app.module.ts (C:\Self\TFS\CRMMVC01\AngularFirebase\testProject\dist\testProject\server\main.js:237710:25)
    at __webpack_require__ (C:\Self\TFS\CRMMVC01\AngularFirebase\testProject\dist\testProject\server\main.js:26:30)
    at Object../src/app/app.server.module.ts (C:\Self\TFS\CRMMVC01\AngularFirebase\testProject\dist\testProject\server\main.js:237832:22)

A server error has occurred.
node exited with 1 code.
connect ECONNREFUSED 127.0.0.1:64286_

_C:\Self\TFS\CRMMVC01\AngularFirebase\testProject\dist\testProject\server\main.js:228691
                                __WEBPACK_AMD_DEFINE_RESULT__ !== undefined && (module.exports = __WEBPACK_AMD_DEFINE_RESULT__));a.WebDataRocks=b()})(window,function(){return function(a){'use strict';var n;
                                                                                                                                                      ^

ReferenceError: window is not defined
    at Object.<anonymous> (C:\Self\TFS\CRMMVC01\AngularFirebase\testProject\dist\testProject\server\main.js:228691:123)
    at Object../src/app/app.server.module.ts (C:\Self\TFS\CRMMVC01\AngularFirebase\testProject\dist\testProject\server\main.js:237809:22)
    at __webpack_require__ (C:\Self\TFS\CRMMVC01\AngularFirebase\testProject\dist\testProject\server\main.js:26:30)
    at Object../src/main.server.ts (C:\Self\TFS\CRMMVC01\AngularFirebase\testProject\dist\testProject\server\main.js:237892:27)

A server error has occurred.
node exited with 1 code.
connect ECONNREFUSED 127.0.0.1:52135_

What should I do now and can u just guide me how to install for ANGULAR UNIVERSAL based projects

**Comment by solja484** [comment]
Please note that WebDataRocks is not compatible with server-side rendering. So, we recommend using the component from the client side.

**Comment by LarozeMultiservices** [comment]
@solja484  I wasn't tried to connect or run on SERVER-SIDE RENDERING. 

1. My project was configured with ANGULAR UNVIERSAL.
2.  Is that possible to use WEBDATAROCKS. 

If it so just help me because I tried and end with the above errors...!

**Comment by solja484** [comment]
As far as we know, Angular Universal is a technology that renders Angular applications on the server.
For now, we don't have an example for using WebDataRocks with Angular Universal. You can walk through the simple Angular example: [https://github.com/WebDataRocks/pivot-angular](https://github.com/WebDataRocks/pivot-angular).
We also know that there were similar problems with Angular 10. Updating your Angular version could also help.
