### ISSUE TITLE
Fails to open local csv file

### ISSUE THREAD

**Issue by elmasbestia** [WebDataRocks/web-pivot-table#20]
webdatarocks.js:1410 Uncaught TypeError: Failed to execute 'readAsText' on 'FileReader': parameter 1 is not of type 'Blob'.
    at u (webdatarocks.js:1410:20947)
    at o.readAsText (webdatarocks.js:1410:21595)
    at k.load (webdatarocks.js:103:305)
    at d.n0 (webdatarocks.js:537:242)
    at k.<anonymous> (webdatarocks.js:536:467)
    at k.na (webdatarocks.js:15:234)
    at k.Oa (webdatarocks.js:16:226)
    at k.S_ (webdatarocks.js:102:494)
    at HTMLInputElement.<anonymous> (webdatarocks.js:102:357)

**Comment by solja484** [comment]
Hello, Rafael!

Could you please provide us with the steps to reproduce the described behavior?
This would help us greatly to continue the investigation.

Regards,
Solomiia
